import { getDashboardMetrics, getTrialsEndingSoon } from "./selectors";
import type { Subscription } from "./types";

export const demoToday = "2026-05-19";

export const sampleSubscriptions: Subscription[] = [
  {
    id: "netflix-premium",
    providerName: "Netflix Premium",
    category: "Streaming",
    status: "Active",
    billingCadence: "Monthly",
    priceAmount: 22.99,
    currency: "USD",
    startDate: "2024-02-12",
    renewalDate: "2026-05-28",
    accountEmailForProvider: "alex@example.com",
    loginUrl: "https://www.netflix.com/login",
    billingUrl: "https://www.netflix.com/account",
    cancelUrl: "https://www.netflix.com/cancelplan",
    supportUrl: "https://help.netflix.com",
    paymentMethodLabel: "Visa ending 1234",
    notes: "Shared with household. Review plan tier before annual vacation.",
    lastUsageDate: "2026-05-16",
    createdAt: "2026-05-19T00:00:00.000Z",
    updatedAt: "2026-05-19T00:00:00.000Z",
  },
  {
    id: "spotify-family",
    providerName: "Spotify Family",
    category: "Music",
    status: "Active",
    billingCadence: "Monthly",
    priceAmount: 19.99,
    currency: "USD",
    startDate: "2023-08-01",
    renewalDate: "2026-06-01",
    accountEmailForProvider: "music@example.com",
    loginUrl: "https://accounts.spotify.com",
    billingUrl: "https://www.spotify.com/account/subscription/",
    cancelUrl: "https://support.spotify.com/article/cancel-premium/",
    supportUrl: "https://support.spotify.com",
    paymentMethodLabel: "Mastercard ending 8080",
    notes: "Family plan. Confirm everyone still uses it this month.",
    lastUsageDate: "2026-05-18",
    createdAt: "2026-05-19T00:00:00.000Z",
    updatedAt: "2026-05-19T00:00:00.000Z",
  },
  {
    id: "icloud-storage",
    providerName: "iCloud Storage",
    category: "Storage",
    status: "Active",
    billingCadence: "Monthly",
    priceAmount: 2.99,
    currency: "USD",
    startDate: "2022-11-20",
    renewalDate: "2026-05-20",
    accountEmailForProvider: "alex@example.com",
    loginUrl: "https://appleid.apple.com",
    billingUrl: "https://support.apple.com/billing",
    cancelUrl: "https://support.apple.com/icloud",
    supportUrl: "https://support.apple.com",
    paymentMethodLabel: "Apple Pay",
    notes: "Tiny but easy to forget. Keep while photo library sync is active.",
    lastUsageDate: "2026-05-19",
    createdAt: "2026-05-19T00:00:00.000Z",
    updatedAt: "2026-05-19T00:00:00.000Z",
  },
  {
    id: "adobe-creative-cloud",
    providerName: "Adobe Creative Cloud",
    category: "Software",
    status: "Active",
    billingCadence: "Yearly",
    priceAmount: 659.88,
    currency: "USD",
    startDate: "2025-09-15",
    renewalDate: "2026-09-15",
    accountEmailForProvider: "design@example.com",
    loginUrl: "https://account.adobe.com",
    billingUrl: "https://account.adobe.com/plans",
    cancelUrl: "https://helpx.adobe.com/manage-account/using/cancel-subscription.html",
    supportUrl: "https://helpx.adobe.com/support.html",
    paymentMethodLabel: "Amex ending 4411",
    notes: "Annual renewal. Check alternatives before September.",
    lastUsageDate: "2026-05-02",
    createdAt: "2026-05-19T00:00:00.000Z",
    updatedAt: "2026-05-19T00:00:00.000Z",
  },
  {
    id: "notion-plus-trial",
    providerName: "Notion Plus Trial",
    category: "Software",
    status: "Trial",
    billingCadence: "Monthly",
    priceAmount: 0,
    currency: "USD",
    startDate: "2026-05-05",
    renewalDate: "2026-05-27",
    trialStartDate: "2026-05-05",
    trialEndDate: "2026-05-29",
    cancelByDate: "2026-05-27",
    postTrialPriceAmount: 12,
    accountEmailForProvider: "ops@example.com",
    loginUrl: "https://www.notion.so/login",
    billingUrl: "https://www.notion.so/my-account",
    cancelUrl: "https://www.notion.so/help",
    supportUrl: "https://www.notion.so/help",
    paymentMethodLabel: "Visa ending 1234",
    notes: "Trial converts at $12/month. Decide after workspace review.",
    lastUsageDate: "2026-05-12",
    createdAt: "2026-05-19T00:00:00.000Z",
    updatedAt: "2026-05-19T00:00:00.000Z",
  },
  {
    id: "gym-membership",
    providerName: "Local Gym",
    category: "Health",
    status: "Paused",
    billingCadence: "Weekly",
    priceAmount: 14.5,
    currency: "USD",
    startDate: "2024-01-04",
    renewalDate: "2026-05-26",
    accountEmailForProvider: "alex@example.com",
    loginUrl: null,
    billingUrl: null,
    cancelUrl: null,
    supportUrl: "mailto:support@example-gym.invalid",
    paymentMethodLabel: "Debit ending 0099",
    notes: "Paused while traveling. Confirm pause does not expire.",
    lastUsageDate: "2026-03-03",
    createdAt: "2026-05-19T00:00:00.000Z",
    updatedAt: "2026-05-19T00:00:00.000Z",
  },
];

export function getSampleDashboard() {
  return {
    metrics: getDashboardMetrics(sampleSubscriptions, demoToday),
    renewals: sampleSubscriptions
      .filter((subscription) => subscription.renewalDate)
      .sort((left, right) =>
        String(left.renewalDate).localeCompare(String(right.renewalDate)),
      )
      .slice(0, 5),
    trials: getTrialsEndingSoon(sampleSubscriptions, demoToday, 14),
  };
}

export function getSampleSubscription(id: string): Subscription | undefined {
  return sampleSubscriptions.find((subscription) => subscription.id === id);
}
